config/routes.rb
Rails.application.routes.draw do
  root 'inquiries#new'
  post 'inquiries/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

	validates :name, presence: true
	validates :email, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/ }
	validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
  	  @inquiry = Inquiry.new
  end

  def create
  	  @inquiry = Inquiry.new(inquiry_params)
  	  if @inquiry.save
  	  redirect_to root_path
      InquiryMailer.send_mail(@inquiry).deliver
      InquiryMailer.received_mail(@inquiry).deliver

      else
      render "new"

      end

  end

  def inquiry_params
  	  params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="d-flex justify-content-center">
				<h1 style="margin: 40px 0 20px 0 ;">お問い合わせページです</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<div class="d-flex justify-content-center">
				<h3 class="Note-title">注意点</h3>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-10 offset-2">
			<p>１、名前、メールアドレス、メッセージが全て記入されていないとお問合せできません。ご注意ください。</p>
			<p>２、メールアドレスは半角で入力してください。</p>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<div class="d-flex justify-content-center">
				<%= form_for @inquiry, :url => inquiries_create_path, remote: true do |f| %>
					<div class="form-group">
						<%= f.label :名前 %>
     				    <%= f.text_area :name, id: "send-name", class: "form-control", rows: 1, placeholder: "お名前記入欄" %>
    				</div>
    				<div class="form-group">
						<%= f.label :メールアドレス %>
     				    <%= f.email_field :email, id: "send-email", class: "form-control", rows: 1, placeholder: "メールアドレス記入欄" %>
    				</div>
    				<div class="form-group">
						<%= f.label :メッセージ %>
     				    <%= f.text_area :message, id: "send-message", class: "form-control", rows: 9, cols: 60, placeholder: "メッセージ記入欄" %>
    				</div>
    				<div class="form-submit" style="margin-bottom: 20px;">
      					<%= f.submit "問い合わせをする", class: "form-button" %>
    				</div>
    				<!-- <a href="#", id="send-mail" class="btn btn-info">お問合せをする</a> -->
				<% end %>
			</div>
		</div>
	</div>
</div>
<script>
	$(function(){
		$('.form-button').click(function() {

	    // フォームから入力値を取得
	    var name = $('#send-name').val();
	    var email = $('#send-email').val();
	    var message = $('#send-message').val();

	    // 入力内容の確認
	    if(name != "" && email != "" && message != ""){

	        toastr.options = {
              "closeButton": true,
              "debug": false,
              "newestOnTop": false,
              "progressBar": false,
              "positionClass": "toast-top-center",
              "preventDuplicates": false,
              "showDuration": "300",
              "hideDuration": "1000",
              "timeOut": "5000",
              "extendedTimeOut": "1000",
              "showEasing": "swing",
              "hideEasing": "linear",
              "showMethod": "fadeIn",
              "hideMethod": "fadeOut"
            }
            Command: toastr["warning"]("お問合せありがとうございます。")

	    } else {
	      toastr.options = {
              "closeButton": true,
              "debug": false,
              "newestOnTop": false,
              "progressBar": false,
              "positionClass": "toast-top-center",
              "preventDuplicates": false,
              "showDuration": "300",
              "hideDuration": "1000",
              "timeOut": "5000",
              "extendedTimeOut": "1000",
              "showEasing": "swing",
              "hideEasing": "linear",
              "showMethod": "fadeIn",
              "hideMethod": "fadeOut"
            }
         Command: toastr["error"]("お問い合わせに失敗しました。空欄がないか確認してください。")
	    }

	    });
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contactform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>